name: Log workflow run metrics
on:
  workflow_run:
    workflows: [Main]
    types:
      - completed

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Get the workflow run
        run: |
          swift run GithubActionsMetricsCLI                            \ 
            "${{ github.event.workflow_run.name }}"                    \
            "${{ github.event.workflow_run.updated_at }}"              \
            "${{ github.event.workflow_run.run_started_at }}"          \ 
            "${{ github.event.workflow_run.head_repository.name }}"    \ 
            "${{ github.event.workflow_run.conclusion }}"              \ 
            "${{ github.event.workflow_run.head_commit.author.name }}"
